show @@session
show @@connection.sql
show @@connection
show @@backend
show @@command
show @@heartbeat
show @@database
show @@datanode
show @@datasource
show @@datasource.synstatus
show @@processor
show @@help
show @@server
show @@sysparam
show @@threadpool
show @@time.current
show @@time.startup
show @@version
