#!default_db:schema1
drop table if exists sharding_4_t1
CREATE TABLE sharding_4_t1(ID INT NOT NULL,FirstName VARCHAR(20),LastName VARCHAR(20),Department VARCHAR(20),Salary INT)
INSERT INTO sharding_4_t1 VALUES(1,'Mazojys','Fxoj','Finance',7800),(2,'Jozzh','Lnanyo','Finance',45800),(3,'Syllauu','Dfaafk','Finance',57000),(4,'Gecrrcc','Srlkrt','Finance',62000),(5,'Jssme','Bdnaa','Development',75000),(6,'Dnnaao','Errllov','Development',55000),(7,'Tyoysww','Osk','Development',49000)
drop table if exists sharding_enum_t1
CREATE TABLE `sharding_enum_t1`(`id` int(11) DEFAULT NULL,`name` varchar(50) DEFAULT NULL,age int(11)) ENGINE=InnoDB DEFAULT CHARSET=utf8
insert into sharding_enum_t1(id,name,age) values(1,'sam',20),(2,'AA',50),(3,'BB',60),(4,'CC',135),(5,'DD',25),(6,'FF',17),(7,'EE',15)

select a.FirstName,a.LastName,a.Department,a.Salary,b.* from sharding_4_t1 a,sharding_enum_t1 b where a.id=b.id
select a.FirstName,a.LastName,a.Department,a.Salary,b.* from sharding_4_t1 a left join sharding_enum_t1 b on a.id=b.id
select a.FirstName,a.LastName,a.Department,a.Salary,b.* from sharding_4_t1 a left join sharding_enum_t1 b on a.id=b.id where a.Department='Finance'
select Name,FirstName,LastName,Department,Salary from sharding_enum_t1 a, sharding_4_t1 b where a.id=b.ID order by a.id
select Name,FirstName,LastName,Department,Salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID order by a.id
select Name,FirstName,LastName,Department,Salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID order by a.id
select Name,FirstName,LastName,Department,Salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID order by a.id
select Name,FirstName,LastName,Department,Salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID order by a.id limit 3
select Name,FirstName,LastName,Department,Salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID order by a.id limit 1,4
select Name,FirstName,LastName,Department,Salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID order by a.id limit 1,100
select Name,FirstName,LastName,Department,Salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID order by a.id limit 1 offset 4
select Name,FirstName,LastName,Department,Salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id =5 order by a.id
select Name,FirstName,LastName,Department,Salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id =5 order by a.id
select Name,FirstName,LastName,Department,Salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id >0 order by a.id
select Name,FirstName,LastName,Department,Salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id >0 order by a.id
select Name,FirstName,LastName,Department,Salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id >0 and a.id <4 order by a.id
select Name,FirstName,LastName,Department,Salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id >=0 and a.id <=4 order by a.id
select Name,FirstName,LastName,Department,Salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id <>0 and a.id <=4 order by a.id
select Name,FirstName,LastName,Department,Salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id >0 and a.id <4 order by a.id
select Name,FirstName,LastName,Department,Salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id >=0 and a.id <=4 order by a.id
select Name,FirstName,LastName,Department,Salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID order by a.id
select Name,FirstName,LastName,Department,Salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id <>0 and a.id <=4 order by a.id
select Name,FirstName,LastName,Department,Salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id >0 and a.id <4 order by a.id
select Name,FirstName,LastName,Department,Salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id >=0 and a.id <=4 order by a.id
select Name,FirstName,LastName,Department,Salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id >0 order by a.id
select Name,FirstName,LastName,Department,Salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id =5 order by a.id
select Name,FirstName,LastName,Department,Salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id <>0 and a.id <=4 order by a.id
select Name,FirstName,LastName,Department,Salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id >0 and a.id <4 order by a.id
select Name,FirstName,LastName,Department,Salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id >=0 and a.id <=4 order by a.id
select Name,FirstName,LastName,Department,Salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id >0 order by a.id
select Name,FirstName,LastName,Department,Salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id =5 order by a.id
select Department,Sum(age) sum_age from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID group by Department order by a.id
select * from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID order by a.id
select * from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID order by a.id
select * from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID order by a.id
select * from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID order by a.id
select a.id,name,age,FirstName,LastName,Department,Salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID order by a.id
select a.id,name,age,FirstName,LastName,Department,Salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID order by a.id
select a.id,name,age,FirstName,LastName,Department,Salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID order by a.id
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID group by Department order by a.id
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID group by Department order by a.id
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID group by Department order by a.id
select Department,min(age) min_age,max(Salary) max_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID group by Department order by a.id
select Department,min(age) min_age,sum(Salary) sum_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID group by Department order by a.id
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID group by Department order by a.id
select Department,avg(age) avg_age,max(Salary) max_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID group by Department order by a.id
select Department,avg(age) avg_age,sum(Salary) sum_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID group by Department order by a.id
select Department,count(age) count_age from sharding_enum_t1 a join sharding_4_t1 b on a.id=b.ID group by Department order by a.id
select Department,Sum(age) sum_age from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID group by Department order by a.id
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID group by Department order by a.id
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID group by Department order by a.id
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID group by Department order by a.id
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID group by Department order by a.id
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID group by Department order by a.id
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID group by Department order by a.id
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID group by Department order by a.id
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID group by Department order by a.id
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID group by Department order by a.id
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID group by Department order by a.id
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID group by Department order by a.id
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID group by Department order by a.id
select Department,count(age) count_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID group by Department order by a.id
select Department,count(age) count_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID group by Department order by a.id
select Department,count(age) count_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID group by Department order by a.id
select * from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and b.Department='Finance' order by a.id
select * from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where b.Department='Finance' order by a.id
select * from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where b.Department='Finance' order by a.id
select * from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where b.Department='Finance' order by a.id
select a.id,name,age,FirstName,LastName,Department,Salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where b.Department='Finance' order by a.id
select a.id,name,age,FirstName,LastName,Department,Salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where b.Department='Finance' order by a.id
select a.id,name,age,FirstName,LastName,Department,Salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where b.Department='Finance' order by a.id
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and b.Department='Finance' order by a.id
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and b.Department='Finance' order by a.id
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and b.Department='Finance' order by a.id
select Department,min(age) min_age,max(Salary) max_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and b.Department='Finance' order by a.id
select Department,min(age) min_age,sum(Salary) sum_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and b.Department='Finance' order by a.id
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID and b.Department='Finance' order by a.id
select Department,avg(age) avg_age,max(Salary) max_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID and b.Department='Finance' order by a.id
select Department,avg(age) avg_age,sum(Salary) sum_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where b.Department='Finance' order by a.id
select Department,count(age) count_age from sharding_enum_t1 a join sharding_4_t1 b on a.id=b.ID where b.Department='Finance' order by a.id
select Department,Sum(age) sum_age from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where b.Department='Finance' order by a.id
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where b.Department='Finance' order by a.id
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where b.Department='Finance' order by a.id
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where b.Department='Finance' order by a.id
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where b.Department='Finance' order by a.id
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where b.Department='Finance' order by a.id
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where b.Department='Finance' order by a.id
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where b.Department='Finance' order by a.id
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where b.Department='Finance' order by a.id
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where b.Department='Finance' order by a.id
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where b.Department='Finance' order by a.id
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where b.Department='Finance' order by a.id
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where b.Department='Finance' order by a.id
select Department,count(age) count_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where b.Department='Finance' order by a.id
select Department,count(age) count_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where b.Department='Finance' order by a.id
select Department,count(age) count_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where b.Department='Finance' order by a.id
select * from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and b.Department in ('Finance','Development') order by a.id
select * from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') order by a.id
select * from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') order by a.id
select * from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') order by a.id
select a.id,name,age,FirstName,LastName,Department,Salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') order by a.id
select a.id,name,age,FirstName,LastName,Department,Salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') order by a.id
select a.id,name,age,FirstName,LastName,Department,Salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') order by a.id
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and b.Department in ('Finance','Development') group by Department order by a.id
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and b.Department in ('Finance','Development') group by Department order by a.id
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and b.Department in ('Finance','Development') group by Department order by a.id
select Department,min(age) min_age,max(Salary) max_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and b.Department in ('Finance','Development') group by Department order by a.id
select Department,min(age) min_age,sum(Salary) sum_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and b.Department in ('Finance','Development') group by Department order by a.id
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID and b.Department in ('Finance','Development') group by Department order by a.id
select Department,avg(age) avg_age,max(Salary) max_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID and b.Department in ('Finance','Development') group by Department order by a.id
select Department,avg(age) avg_age,sum(Salary) sum_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID and b.Department in ('Finance','Development') group by Department order by a.id
select Department,count(age) count_age from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') group by Department order by a.id
select Department,Sum(age) sum_age from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') group by Department order by a.id
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') group by Department order by a.id
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') group by Department order by a.id
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') group by Department order by a.id
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') group by Department order by a.id
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') group by Department order by a.id
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') group by Department order by a.id
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') group by Department order by a.id
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') group by Department order by a.id
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') group by Department order by a.id
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') group by Department order by a.id
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') group by Department order by a.id
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') group by Department order by a.id
select Department,count(age) count_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') group by Department order by a.id
select Department,count(age) count_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') group by Department order by a.id
select Department,count(age) count_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') group by Department order by a.id
select * from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and b.Department in ('Finance','Development') and b.Salary >500 order by a.id
select * from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') and b.Salary >500 order by a.id
select * from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') and b.Salary >500 order by a.id
select * from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') and b.Salary >500 order by a.id
select a.id,name,age,FirstName,LastName,Department,Salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') and b.Salary >500 order by a.id
select a.id,name,age,FirstName,LastName,Department,Salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') and b.Salary >500 order by a.id
select a.id,name,age,FirstName,LastName,Department,Salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') and b.Salary >500 order by a.id
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and b.Department in ('Finance','Development') and b.Salary >500 group by Department order by a.id
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and b.Department in ('Finance','Development') and b.Salary >500 group by Department order by a.id
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and b.Department in ('Finance','Development') and b.Salary >500 group by Department order by a.id
select Department,min(age) min_age,max(Salary) max_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and b.Department in ('Finance','Development') and b.Salary >500 group by Department order by a.id
select Department,min(age) min_age,sum(Salary) sum_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and b.Department in ('Finance','Development') and b.Salary >500 group by Department order by a.id
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID and b.Department in ('Finance','Development') and b.Salary >500 group by Department order by a.id
select Department,avg(age) avg_age,max(Salary) max_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID and b.Department in ('Finance','Development') and b.Salary >500 group by Department order by a.id
select Department,avg(age) avg_age,sum(Salary) sum_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID and b.Department in ('Finance','Development') and b.Salary >500 group by Department order by a.id
select Department,count(age) count_age from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') and b.Salary >500 group by Department order by a.id
select Department,Sum(age) sum_age from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') and b.Salary >500 group by Department order by a.id
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') and b.Salary >500 group by Department order by a.id
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') and b.Salary >500 group by Department order by a.id
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') and b.Salary >500 group by Department order by a.id
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') and b.Salary >500 group by Department order by a.id
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') and b.Salary >500 group by Department order by a.id
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') and b.Salary >500 group by Department order by a.id
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') and b.Salary >500 group by Department order by a.id
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') and b.Salary >500 group by Department order by a.id
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') and b.Salary >500 group by Department order by a.id
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') and b.Salary >500 group by Department order by a.id
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') and b.Salary >500 group by Department order by a.id
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') and b.Salary >500 group by Department order by a.id
select Department,count(age) count_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') and b.Salary >500 group by Department order by a.id
select Department,count(age) count_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') and b.Salary >500 group by Department order by a.id
select Department,count(age) count_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') and b.Salary >500 group by Department order by a.id
select * from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and b.Department in ('Finance','Development') and b.Salary >500 and b.Salary<70000 order by a.id
select * from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') and b.Salary >500 and b.Salary<70000 order by a.id
select * from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') and b.Salary >500 and b.Salary<70000 order by a.id
select * from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') and b.Salary >500 and b.Salary<70000 order by a.id
select a.id,name,age,FirstName,LastName,Department,Salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') and b.Salary >500 and b.Salary<70000 order by a.id
select a.id,name,age,FirstName,LastName,Department,Salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') and b.Salary >500 and b.Salary<70000 order by a.id
select a.id,name,age,FirstName,LastName,Department,Salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') and b.Salary >500 and b.Salary<70000 order by a.id
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and b.Department in ('Finance','Development') and b.Salary >500 and b.Salary<70000 group by Department order by a.id
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and b.Department in ('Finance','Development') and b.Salary >500 and b.Salary<70000 group by Department order by a.id
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and b.Department in ('Finance','Development') and b.Salary >500 and b.Salary<70000 group by Department order by a.id
select Department,min(age) min_age,max(Salary) max_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and b.Department in ('Finance','Development') and b.Salary >500 and b.Salary<70000 group by Department order by a.id
select Department,min(age) min_age,sum(Salary) sum_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and b.Department in ('Finance','Development') and b.Salary >500 and b.Salary<70000 group by Department order by a.id
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID and b.Department in ('Finance','Development') and b.Salary >500 and b.Salary<70000 group by Department order by a.id
select Department,avg(age) avg_age,max(Salary) max_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID and b.Department in ('Finance','Development') and b.Salary >500 and b.Salary<70000 group by Department order by a.id
select Department,avg(age) avg_age,sum(Salary) sum_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID and b.Department in ('Finance','Development') and b.Salary >500 and b.Salary<70000 group by Department order by a.id/*allow_diff_sequence*/
select Department,count(age) count_age from sharding_enum_t1 a join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') and b.Salary >500 and b.Salary<70000 group by Department order by a.id
select Department,Sum(age) sum_age from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') and b.Salary >500 and b.Salary<70000 order by a.id
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') and b.Salary >500 and b.Salary<70000 group by Department order by a.id
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') and b.Salary >500 and b.Salary<70000 group by Department order by a.id
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') and b.Salary >500 and b.Salary<70000 group by Department order by a.id
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') and b.Salary >500 and b.Salary<70000 group by Department order by a.id
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') and b.Salary >500 and b.Salary<70000 group by Department order by a.id
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') and b.Salary >500 and b.Salary<70000 group by Department order by a.id
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') and b.Salary >500 and b.Salary<70000 group by Department order by a.id
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') and b.Salary >500 and b.Salary<70000 group by Department order by a.id
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') and b.Salary >500 and b.Salary<70000 group by Department order by a.id
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') and b.Salary >500 and b.Salary<70000 group by Department order by a.id
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') and Salary >500 and b.Salary<70000  group by Department order by a.id
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') and b.Salary >500 and b.Salary<70000 group by Department order by a.id
select Department,count(age) count_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') and b.Salary >500 and b.Salary<70000 group by Department order by a.id
select Department,count(age) count_age,max(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') and b.Salary >500 and b.Salary<70000 group by Department order by a.id
select Department,count(age) count_age,min(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where b.Department in ('Finance','Development') and b.Salary >500 and b.Salary<70000 group by Department order by a.id
select * from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and a.id in (1,3,5,7) and b.Salary >500 and b.Salary<70000 order by a.id
select * from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,3,5,7) and b.Salary >500 and b.Salary<70000 order by a.id
select * from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id in (1,3,5,7) and b.Salary >500 and b.Salary<70000 order by a.id
select * from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,3,5,7) and b.Salary >500 and b.Salary<70000 order by a.id
select a.id,name,age,FirstName,LastName,Department,Salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,3,5,7) and b.Salary >500 and b.Salary<70000 order by a.id
select a.id,name,age,FirstName,LastName,Department,Salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id in (1,3,5,7) and b.Salary >500 and b.Salary<70000 order by a.id
select a.id,name,age,FirstName,LastName,Department,Salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,3,5,7) and b.Salary >500 and b.Salary<70000 order by a.id
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and a.id in (1,3,5,7) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and a.id in (1,3,5,7) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and a.id in (1,3,5,7) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select Department,min(age) min_age,max(Salary) max_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and a.id in (1,3,5,7) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select Department,min(age) min_age,sum(Salary) sum_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and a.id in (1,3,5,7) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID and a.id in (1,3,5,7) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select Department,avg(age) avg_age,max(Salary) max_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID and a.id in (1,3,5,7) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select Department,avg(age) avg_age,sum(Salary) sum_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID and a.id in (1,3,5,7) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select Department,count(age) count_age from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,3,5,7) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select Department,Sum(age) sum_age from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,3,5,7) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,3,5,7) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id in (1,3,5,7) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,3,5,7) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,3,5,7) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id in (1,3,5,7) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,3,5,7) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,3,5,7) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id in (1,3,5,7) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,3,5,7) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,3,5,7) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id in (1,3,5,7) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,3,5,7) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select Department,count(age) count_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,3,5,7) and b.Salary >500 and  b.Salary<70000 group by Department order by Department
select Department,count(age) count_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id in (1,3,5,7) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select Department,count(age) count_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,3,5,7) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select * from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 order by a.id
select * from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 order by a.id
select * from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 order by a.id
select * from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 order by a.id
select a.id,name,age,FirstName,LastName,Department,Salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 order by a.id
select a.id,name,age,FirstName,LastName,Department,Salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 order by a.id
select a.id,name,age,FirstName,LastName,Department,Salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 order by a.id
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select Department,min(age) min_age,max(Salary) max_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select Department,min(age) min_age,sum(Salary) sum_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select Department,avg(age) avg_age,max(Salary) max_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select Department,avg(age) avg_age,sum(Salary) sum_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select Department,count(age) count_age from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select Department,Sum(age) sum_age from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select Department,count(age) count_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select Department,count(age) count_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select Department,count(age) count_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by Department order by Department
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,min(age) min_age,max(Salary) max_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,min(age) min_age,sum(Salary) sum_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,avg(age) avg_age,max(Salary) max_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,avg(age) avg_age,sum(Salary) sum_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,count(age) count_age from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,Sum(age) sum_age from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,count(age) count_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,count(age) count_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,count(age) count_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
SELECT Department,avg(age) as avg_age,avg(salary) avg_salary  FROM (SELECT a.id,name,age,Department,salary FROM sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where salary >=500 and age <=150 order by Department DESC) AS Actions GROUP BY Department ORDER BY Department ASC
SELECT Department,avg(age) as avg_age,avg(salary) avg_salary  FROM (SELECT a.id,name,age,Department,salary FROM sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where salary >=500 and age <=150 order by Department DESC) AS Actions GROUP BY Department ORDER BY Department DESC
SELECT Department,avg(age) as avg_age,avg(salary) avg_salary  FROM (SELECT a.id,name,age,Department,salary FROM sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where salary >=500 and age <=150 order by Department DESC) AS Actions GROUP BY Department ORDER BY Department ASC
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,min(age) min_age,max(Salary) max_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,min(age) min_age,sum(Salary) sum_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,avg(age) avg_age,max(Salary) max_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,avg(age) avg_age,sum(Salary) sum_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,count(age) count_age from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,Sum(age) sum_age from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,count(age) count_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,count(age) count_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,count(age) count_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having count(*)>2 order by Department
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b where a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having sum(age)>15 order by Department
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having sum(age)>2 order by Department
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having sum(age)>15 order by Department
select Department,min(age) min_age,max(Salary) max_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having sum(age)>18 order by Department
select Department,min(age) min_age,sum(Salary) sum_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having sum(Salary)>15000 order by Department
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having sum(Salary)>15000 order by Department
select Department,avg(age) avg_age,max(Salary) max_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having sum(Salary)>5000 order by Department
select Department,avg(age) avg_age,sum(Salary) sum_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having sum(Salary)>20000 order by Department
select Department,count(age) count_age from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having sum(salary)>2 order by Department
select Department,Sum(age) sum_age from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having sum(salary)>2 order by Department
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having sum(salary)>2 order by Department
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having sum(salary)>2 order by Department
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having sum(salary)>2 order by Department
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having sum(salary)>2 order by Department
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having sum(salary)>2 order by Department
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having sum(salary)>2 order by Department
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having sum(salary)>2 order by Department
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having sum(salary)>2 order by Department
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having sum(salary)>2 order by Department
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having sum(salary)>2 order by Department
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having sum(salary)>2 order by Department
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having sum(salary)>2 order by Department
select Department,count(age) count_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having sum(salary)>2 order by Department
select Department,count(age) count_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having sum(salary)>2 order by Department
select Department,count(age) count_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having sum(salary)>2 order by Department
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having max(salary)>10000 order by Department
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having max(salary)>10000 order by Department
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having max(salary)>10000 order by Department
select Department,min(age) min_age,max(Salary) max_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having max(salary)>10000 order by Department
select Department,min(age) min_age,sum(Salary) sum_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having max(salary)>10000 order by Department
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having max(salary)>10000 order by Department
select Department,avg(age) avg_age,max(Salary) max_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having max(salary)>10000 order by Department
select Department,avg(age) avg_age,sum(Salary) sum_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having max(salary)>10000 order by Department
select Department,count(age) count_age from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having max(salary)>10000 order by Department
select Department,Sum(age) sum_age from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having max(salary)>10000 order by Department
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having max(salary)>10000 order by Department
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having max(salary)>10000 order by Department
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having max(salary)>10000 order by Department
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having max(salary)>10000 order by Department
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having max(salary)>10000 order by Department
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having max(salary)>10000 order by Department
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having max(salary)>10000 order by Department
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having max(salary)>10000 order by Department
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having max(salary)>10000 order by Department
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having max(salary)>10000 order by Department
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having max(salary)>10000 order by Department
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having max(salary)>10000 order by Department
select Department,count(age) count_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having max(salary)>10000 order by Department
select Department,count(age) count_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having max(salary)>10000 order by Department
select Department,count(age) count_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having max(salary)>10000 order by Department
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having min(salary)>5000 order by Department
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having min(salary)>5000 order by Department
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having min(salary)>5000 order by Department
select Department,min(age) min_age,max(Salary) max_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having min(salary)>5000 order by Department
select Department,min(age) min_age,sum(Salary) sum_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having min(salary)>5000 order by Department
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having min(salary)>5000 order by Department
select Department,avg(age) avg_age,max(Salary) max_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having min(salary)>5000 order by Department
select Department,avg(age) avg_age,sum(Salary) sum_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having min(salary)>5000 order by Department
select Department,count(age) count_age from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having min(salary)>5000 order by Department
select Department,Sum(age) sum_age from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having min(salary)>5000 order by Department
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having min(salary)>5000 order by Department
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having min(salary)>5000 order by Department
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having min(salary)>5000 order by Department
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having min(salary)>5000 order by Department
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having min(salary)>5000 order by Department
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having min(salary)>5000 order by Department
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having min(salary)>5000 order by Department
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having min(salary)>5000 order by Department
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having min(salary)>5000 order by Department
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having min(salary)>5000 order by Department
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having min(salary)>5000 order by Department
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having min(salary)>5000 order by Department
select Department,count(age) count_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having min(salary)>5000 order by Department
select Department,count(age) count_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having min(salary)>5000 order by Department
select Department,count(age) count_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having min(salary)>5000 order by Department
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having avg(salary)>15000 order by Department
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having avg(salary)>15000 order by Department
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having avg(salary)>15000 order by Department
select Department,min(age) min_age,max(Salary) max_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having avg(salary)>15000 order by Department
select Department,min(age) min_age,sum(Salary) sum_salary from sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having avg(salary)>15000 order by Department
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having avg(salary)>15000 order by Department
select Department,avg(age) avg_age,max(Salary) max_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having avg(salary)>15000 order by Department
select Department,avg(age) avg_age,sum(Salary) sum_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID and a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having avg(salary)>15000 order by Department
select Department,count(age) count_age from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having avg(salary)>15000 order by Department
select Department,Sum(age) sum_age from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having avg(salary)>15000 order by Department
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having avg(salary)>15000 order by Department
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having avg(salary)>15000 order by Department
select Department,Sum(age) sum_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having avg(salary)>15000 order by Department
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having avg(salary)>15000 order by Department
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having avg(salary)>15000 order by Department
select Department,max(age) max_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having avg(salary)>15000 order by Department
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having avg(salary)>15000 order by Department
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having avg(salary)>15000 order by Department
select Department,min(age) min_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having avg(salary)>15000 order by Department
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having avg(salary)>15000 order by Department
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having avg(salary)>15000 order by Department
select Department,avg(age) avg_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having avg(salary)>15000 order by Department
select Department,count(age) count_age,avg(Salary) avg_salary from sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having avg(salary)>15000 order by Department
select Department,count(age) count_age,avg(Salary) avg_salary from sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having avg(salary)>15000 order by Department
select Department,count(age) count_age,avg(Salary) avg_salary from sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where a.id in (1,6,3,8,5,2,7,4) and b.Salary >500 and b.Salary<70000 group by b.Department having avg(salary)>15000 order by Department
SELECT Department,max(age) as max_age,sum(salary) sum_salary  FROM (SELECT a.id,name,age,Department,salary FROM sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where salary >=500 and age <=150 order by Department DESC) AS Actions GROUP BY Department ORDER BY Department ASC/*allow_diff_sequence*/
SELECT Department,max(age) as max_age,sum(salary) sum_salary  FROM (SELECT a.id,name,age,Department,salary FROM sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where salary >=500 and age <=150 order by Department DESC) AS Actions GROUP BY Department ORDER BY Department ASC/*allow_diff_sequence*/
SELECT Department,max(age) as max_age,sum(salary) sum_salary  FROM (SELECT a.id,name,age,Department,salary FROM sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where salary >=500 and age <=150 order by Department DESC) AS Actions GROUP BY Department ORDER BY Department ASC/*allow_diff_sequence*/
SELECT Department,min(age) as min_age,sum(salary) sum_salary  FROM (SELECT a.id,name,age,Department,salary FROM sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where salary >=500 and age <=150 order by Department DESC) AS Actions GROUP BY Department ORDER BY Department ASC/*allow_diff_sequence*/
SELECT Department,min(age) as min_age,sum(salary) sum_salary  FROM (SELECT a.id,name,age,Department,salary FROM sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where salary >=500 and age <=150 order by Department DESC) AS Actions GROUP BY Department ORDER BY Department ASC/*allow_diff_sequence*/
SELECT Department,min(age) as min_age,sum(salary) sum_salary  FROM (SELECT a.id,name,age,Department,salary FROM sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where salary >=500 and age <=150 order by Department DESC) AS Actions GROUP BY Department ORDER BY Department ASC/*allow_diff_sequence*/
SELECT Department,count(age) as min_age,sum(salary) sum_salary  FROM (SELECT a.id,name,age,Department,salary FROM sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where salary >=500 and age <=150 order by Department DESC) AS Actions GROUP BY Department ORDER BY Department ASC/*allow_diff_sequence*/
SELECT Department,count(age) as min_age,sum(salary) sum_salary  FROM (SELECT a.id,name,age,Department,salary FROM sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where salary >=500 and age <=150 order by Department DESC) AS Actions GROUP BY Department ORDER BY age ASC/*allow_diff_sequence*/
SELECT Department,count(age) as min_age,sum(salary) sum_salary  FROM (SELECT a.id,name,age,Department,salary FROM sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where salary >=500 and age <=150 order by Department DESC) AS Actions GROUP BY Department ORDER BY salary ASC/*allow_diff_sequence*/
SELECT Department,max(age) as max_age,avg(salary) sum_salary  FROM (SELECT a.id,name,age,Department,salary FROM sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where salary >=500 and age <=150 order by Department DESC) AS Actions GROUP BY Department ORDER BY salary ASC/*allow_diff_sequence*/
SELECT Department,max(age) as max_age,avg(salary) sum_salary  FROM (SELECT a.id,name,age,Department,salary FROM sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where salary >=500 and age <=150 order by Department DESC) AS Actions GROUP BY Department ORDER BY salary ASC/*allow_diff_sequence*/
SELECT Department,max(age) as max_age,avg(salary) sum_salary  FROM (SELECT a.id,name,age,Department,salary FROM sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where salary >=500 and age <=150 order by Department DESC) AS Actions GROUP BY Department ORDER BY salary ASC/*allow_diff_sequence*/
SELECT Department,min(age) as min_age,avg(salary) sum_salary  FROM (SELECT a.id,name,age,Department,salary FROM sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where salary >=500 and age <=150 order by Department DESC) AS Actions GROUP BY Department ORDER BY salary ASC/*allow_diff_sequence*/
SELECT Department,min(age) as min_age,avg(salary) sum_salary  FROM (SELECT a.id,name,age,Department,salary FROM sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where salary >=500 and age <=150 order by Department DESC) AS Actions GROUP BY Department ORDER BY salary ASC/*allow_diff_sequence*/
SELECT Department,min(age) as min_age,avg(salary) sum_salary  FROM (SELECT a.id,name,age,Department,salary FROM sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where salary >=500 and age <=150 order by Department DESC) AS Actions GROUP BY Department ORDER BY salary ASC/*allow_diff_sequence*/
SELECT Department,count(age) as min_age,avg(salary) sum_salary  FROM (SELECT a.id,name,age,Department,salary FROM sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where salary >=500 and age <=150 order by Department DESC) AS Actions GROUP BY Department ORDER BY salary ASC/*allow_diff_sequence*/
SELECT Department,count(age) as min_age,avg(salary) sum_salary  FROM (SELECT a.id,name,age,Department,salary FROM sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where salary >=500 and age <=150 order by Department DESC) AS Actions GROUP BY Department ORDER BY salary ASC/*allow_diff_sequence*/
SELECT Department,count(age) as min_age,avg(salary) sum_salary  FROM (SELECT a.id,name,age,Department,salary FROM sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where salary >=500 and age <=150 order by Department DESC) AS Actions GROUP BY Department ORDER BY salary ASC/*allow_diff_sequence*/
SELECT Department,max(age) as age,min(salary) salary  FROM (SELECT a.id,name,age,Department,salary FROM sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where salary >=500 and age <=150 order by Department DESC) AS Actions GROUP BY Department ORDER BY salary ASC/*allow_diff_sequence*/
SELECT Department,max(age) as age,min(salary) salary  FROM (SELECT a.id,name,age,Department,salary FROM sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where salary >=500 and age <=150 order by Department DESC) AS Actions GROUP BY Department ORDER BY salary ASC/*allow_diff_sequence*/
SELECT Department,max(age) as age,min(salary) salary  FROM (SELECT a.id,name,age,Department,salary FROM sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where salary >=500 and age <=150 order by Department DESC) AS Actions GROUP BY Department ORDER BY salary ASC/*allow_diff_sequence*/
SELECT Department,min(age) as age,avg(salary) salary  FROM (SELECT a.id,name,age,Department,salary FROM sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where salary >=500 and age <=150 order by Department DESC) AS Actions GROUP BY Department ORDER BY salary ASC/*allow_diff_sequence*/
SELECT Department,min(age) as age,avg(salary) salary  FROM (SELECT a.id,name,age,Department,salary FROM sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where salary >=500 and age <=150 order by Department DESC) AS Actions GROUP BY Department ORDER BY salary ASC/*allow_diff_sequence*/
SELECT Department,min(age) as age,avg(salary) salary  FROM (SELECT a.id,name,age,Department,salary FROM sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where salary >=500 and age <=150 order by Department DESC) AS Actions GROUP BY Department ORDER BY salary ASC/*allow_diff_sequence*/
SELECT Department,sum(age) as age,avg(salary) salary  FROM (SELECT a.id,name,age,Department,salary FROM sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where salary >=500 and age <=150 order by Department DESC) AS Actions GROUP BY Department ORDER BY salary ASC/*allow_diff_sequence*/
SELECT Department,sum(age) as age,avg(salary) salary  FROM (SELECT a.id,name,age,Department,salary FROM sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where salary >=500 and age <=150 order by Department DESC) AS Actions GROUP BY Department ORDER BY salary ASC/*allow_diff_sequence*/
SELECT Department,sum(age) as age,avg(salary) salary  FROM (SELECT a.id,name,age,Department,salary FROM sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where salary >=500 and age <=150 order by Department DESC) AS Actions GROUP BY Department ORDER BY salary ASC/*allow_diff_sequence*/
SELECT name,age,salary,department FROM sharding_enum_t1 a,sharding_4_t1 b where a.id=b.ID and b.ID in (select ID from sharding_4_t1 order by ID)
SELECT name,age,salary,department FROM sharding_enum_t1 a inner join sharding_4_t1 b on a.id=b.ID where b.ID in (select ID from sharding_4_t1 order by ID)
SELECT name,age,salary,department FROM sharding_enum_t1 a left join sharding_4_t1 b on a.id=b.ID where b.ID in (select ID from sharding_4_t1 order by ID)
SELECT name,age,salary,department FROM sharding_enum_t1 a right join sharding_4_t1 b on a.id=b.ID where b.ID in (select ID from sharding_4_t1 order by ID)
#
#clear tables
#
drop table if exists sharding_4_t1
drop table if exists sharding_enum_t1