version: '2.2'
networks:
  dble-net:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.100.9.0/24
          gateway: 172.100.9.8
        - subnet: 2001::/120
          gateway: 2001::8

volumes:
  mysql_1_cgroup: {}
  mysql_2_cgroup: {}
  mysql_cgroup: {}
  dble_1_cgroup: {}
  dble_2_cgroup: {}
  dble_3_cgroup: {}
  # zk_1_data: {}
  # zk_1_datalog: {}
  # zk_2_data: {}
  # zk_2_datalog: {}
  # zk_3_data: {}
  # zk_3_datalog: {}

services:
  mysql-1:
    image: reg.actiontech.com/actiontech/dble_test_mysql
    container_name: mysql-1
    hostname: mysql-1
    privileged: true
    stdin_open: true
    tty: true
    ports:
      - 13306:3306
    networks:
      dble-net:
        ipv4_address: 172.100.9.5
        ipv6_address: 2001::1
    volumes:
      - mysql_1_cgroup:/sys/fs/cgroup
      - /share:/share
     

  mysql-2:
    image: reg.actiontech.com/actiontech/dble_test_mysql
    container_name: mysql-2
    hostname: mysql-2
    privileged: true
    stdin_open: true
    tty: true
    ports:
      - 23306:3306
      - 23307:3307
      - 23308:3308
    networks:
      dble-net:
        ipv4_address: 172.100.9.6
        ipv6_address: 2001::2
    volumes:
      - mysql_2_cgroup:/sys/fs/cgroup
      - /share:/share


  mysql:
    image: reg.actiontech.com/actiontech/dble_test_mysql
    container_name: mysql
    hostname: mysql
    privileged: true
    stdin_open: true
    tty: true
    ports:
      - 3306:3306
      - 3307:3307

    networks:
      dble-net:
        ipv4_address: 172.100.9.4
        ipv6_address: 2001::10
    volumes:
      - mysql_cgroup:/sys/fs/cgroup
      - /share:/share

  dble-1:
    image: reg.actiontech.com/actiontech/dble_test_dble
    container_name: dble-1
    hostname: dble-1
    privileged: true
    stdin_open: true
    tty: true
    ports:
      - 18066:8066
      - 19066:9066 
    networks:
      dble-net:
        ipv4_address: 172.100.9.1
        ipv6_address: 2001::11
    volumes:
      - dble_1_cgroup:/sys/fs/cgroup
      - /share:/share
    working_dir: /opt

  dble-2:
    image: reg.actiontech.com/actiontech/dble_test_dble
    container_name: dble-2
    hostname: dble-2
    privileged: true
    stdin_open: true
    tty: true
    ports:
      - 28066:8066
      - 29066:9066 
    networks:
      dble-net:
        ipv4_address: 172.100.9.2
        ipv6_address: 2001::12
    volumes:
      - dble_2_cgroup:/sys/fs/cgroup
      - /share:/share
    working_dir: /opt

  dble-3:
    image: reg.actiontech.com/actiontech/dble_test_dble
    container_name: dble-3
    hostname: dble-3
    privileged: true
    stdin_open: true
    tty: true
    ports:
      - 38066:8066
      - 39066:9066 
    networks:
      dble-net:
        ipv4_address: 172.100.9.3
        ipv6_address: 2001::13
    volumes:
      - dble_3_cgroup:/sys/fs/cgroup
      - /share:/share
    working_dir: /opt

  # zk-1:
  #   # 有Log4Shell CVE not detected标签的最低版本
  #   image: zookeeper:3.4.14
  #   container_name: zk-1
  #   hostname: zk-1
  #   ports:
  #     - 2181:2181
  #   networks:
  #     dble-net:
  #       ipv4_address: 172.100.9.21
  #       ipv6_address: 2001::21
  #   volumes:
  #     - zk_1_data:/data
  #     - zk_1_datalog:/datalog
  #   environment:
  #     ZOO_MY_ID: 1
      # ZOO_INIT_LIMIT: 10
      # ZOO_SERVERS: server.1=zk-1:2888:3888;2181 server.2=zk-2:2888:3888;2181 server.3=zk-3:2888:3888;2181

  # zk-2:
  #   image: zookeeper:3.4.14
  #   container_name: zk-2
  #   hostname: zk-2
  #   ports:
  #     - 2182:2181
  #   networks:
  #     dble-net:
  #       ipv4_address: 172.100.9.22
  #       ipv6_address: 2001::22
  #   volumes:
  #     - zk_2_data:/data
  #     - zk_2_datalog:/datalog
  #   environment:
  #     ZOO_MY_ID: 2
  #   ZOO_INIT_LIMIT: 10
  #   ZOO_SERVERS: server.1=zk-1:2888:3888;2181 server.2=zk-2:2888:3888;2181 server.3=zk-3:2888:3888;2181

  # zk-3:
  #   image: zookeeper:3.4.14
  #   container_name: zk-3
  #   hostname: zk-3
  #   ports:
  #     - 2183:2181
  #   networks:
  #     dble-net:
  #       ipv4_address: 172.100.9.23
  #       ipv6_address: 2001::23
  #   volumes:
  #     - zk_3_data:/data
  #     - zk_3_datalog:/datalog
  #   environment:
  #     ZOO_MY_ID: 3
  #     ZOO_INIT_LIMIT: 10
  #     ZOO_SERVERS: server.1=zk-1:2888:3888;2181 server.2=zk-2:2888:3888;2181 server.3=zk-3:2888:3888;2181
