From centos:centos7
RUN yum install -y yum-utils device-mapper-persistent-data lvm2 wget gcc g++ git compat-libstdc++ libXtst.i686 gtk2.i686 vi less which net-tools fontconfig libaio hwloc libpciaccess lsof perl-Data-Dumper perl lz4 libunwind python-devel mysql-devel openssh-server
RUN yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
RUN yum install -y docker-ce docker-ce-cli containerd.io
RUN curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
RUN yum install -y epel-release

RUN wget ftp://ftp:ftp@10.186.18.20/housekeep/jdk-8u121-linux-x64.tar.gz
RUN mkdir /opt/jdk
RUN tar -zxvf jdk-8u121-linux-x64.tar.gz -C /opt/jdk --strip-components=1
RUN echo "export JAVA_HOME=/usr/jdk">>/etc/bashrc

RUN wget ftp://ftp:ftp@10.186.18.20/mysql-tarball/mysql-5.7.21-linux-glibc2.12-x86_64.tar.gz
RUN mkdir /usr/local/mysql
RUN tar -zxvf mysql-5.7.21-linux-glibc2.12-x86_64.tar.gz -C /usr/local/mysql --strip-components=1
RUN echo "export PATH=/usr/local/mysql/bin:/opt/jdk/bin:$PATH">>/etc/bashrc


RUN wget ftp://ftp:ftp@10.186.18.20/housekeep/MySql.Data.dll -P /opt
RUN wget ftp://ftp:ftp@10.186.18.20/housekeep/YamlDotNet.dll -P /opt

RUN yum install -y python-pip
RUN yum -y install sysbench
RUN pip install --upgrade pip
RUN curl --request GET -o /opt/dependencies_install.sh --header 'PRIVATE-TOKEN: Yz8U84daRU1cWUij2Mbb' http://10.186.18.21/api/v4/projects/293/repository/files/behave_dble%2Fcompose%2Fdependencies_install.sh/raw?ref=master
RUN curl --request GET -o /opt/dependencies.txt --header 'PRIVATE-TOKEN: Yz8U84daRU1cWUij2Mbb' http://10.186.18.21/api/v4/projects/293/repository/files/behave_dble%2Fcompose%2Fdependencies.txt/raw?ref=master
RUN chmod 777 /opt/dependencies_install.sh
RUN bash dependencies_install.sh dependencies.txt

RUN chmod 777 /usr/local/bin/docker-compose


RUN rpm --import "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF"
RUN curl https://download.mono-project.com/repo/centos7-stable.repo | tee /etc/yum.repos.d/mono-centos7-stable.repo
RUN yum -y install mono-complete

RUN curl --request GET -o /opt/docker-compose.yml --header 'PRIVATE-TOKEN: Yz8U84daRU1cWUij2Mbb' http://10.186.18.21/api/v4/projects/293/repository/files/behave_dble%2Fcompose%2Fdocker-compose-allinone.yml/raw?ref=master
RUN curl --request GET -o /opt/init.sh --header 'PRIVATE-TOKEN: Yz8U84daRU1cWUij2Mbb' http://10.186.18.21/api/v4/projects/293/repository/files/behave_dble%2Fcompose%2Finit.sh/raw?ref=master
RUN chmod 777 /opt/init.sh

RUN ssh-keygen -t rsa -N ""  -f "/root/.ssh/id_rsa"

WORKDIR /opt/
CMD ["/opt/init.sh"]