From centos:centos7
RUN yum install -y yum-utils device-mapper-persistent-data lvm2 wget
RUN yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
RUN yum install -y docker-ce docker-ce-cli containerd.io
RUN curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
RUN yum install -y epel-release 
RUN yum install -y python-pip
RUN yum -y install sysbench
RUN pip install --upgrade pip
RUN pip install allure-behave
RUN chmod 777 /usr/local/bin/docker-compose
RUN curl --request GET -o /opt/docker-compose.yml --header 'PRIVATE-TOKEN: oKLY6Ldx8ZuyTKDCYtPx' http://10.186.18.21/api/v4/projects/171/repository/files/behave_dble%2Fcompose%2Fdocker-compose-allinone.yml/raw?ref=master
RUN curl --request GET -o /opt/init.sh --header 'PRIVATE-TOKEN: oKLY6Ldx8ZuyTKDCYtPx' http://10.186.18.21/api/v4/projects/171/repository/files/behave_dble%2Fcompose%2Finit.sh/raw?ref=master
RUN chmod 777 /opt/init.sh 

WORKDIR /opt/
CMD ["/opt/init.sh"]