version: '2.2'
networks:
  dble-net:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.100.9.0/24
          gateway: 172.100.9.8
        - subnet: 2001:3984:3989::/64
          gateway: 2001:3984:3989::1

volumes:
  mysql_1_cgroup: {}
  mysql_2_cgroup: {}
  mysql_cgroup: {}
  dble_1_cgroup: {}

services:
  mysql-1:
    image: reg.actiontech.com/actiontech/dble_test_mysql
    container_name: mysql-1
    hostname: mysql-1
    privileged: true
    stdin_open: true
    tty: true
    ports:
      - 13306:3306
    networks:
      dble-net:
        ipv4_address: 172.100.9.5
        ipv6_address: 2001:3984:3989::15
    volumes:
      - mysql_1_cgroup:/sys/fs/cgroup
      - /share:/share

  mysql-2:
    image: reg.actiontech.com/actiontech/dble_test_mysql
    container_name: mysql-2
    hostname: mysql-2
    privileged: true
    stdin_open: true
    tty: true
    ports:
      - 23306:3306
      - 23307:3307
      - 23308:3308
    networks:
      dble-net:
        ipv4_address: 172.100.9.6
        ipv6_address: 2001:3984:3989::16
    volumes:
      - mysql_2_cgroup:/sys/fs/cgroup
      - /share:/share

  mysql:
    image: reg.actiontech.com/actiontech/dble_test_mysql
    container_name: mysql
    hostname: mysql
    privileged: true
    stdin_open: true
    tty: true
    ports:
      - 3306:3306
      - 3307:3307
    networks:
      dble-net:
        ipv4_address: 172.100.9.4
        ipv6_address: 2001:3984:3989::14
    volumes:
      - mysql_cgroup:/sys/fs/cgroup
      - /share:/share

  dble-1:
    image: reg.actiontech.com/actiontech/dble_test_dble
    container_name: dble-1
    hostname: dble-1
    privileged: true
    stdin_open: true
    tty: true
    ports:
      - 18066:8066
      - 19066:9066   
    networks:
      dble-net:
        ipv4_address: 172.100.9.1
        ipv6_address: 2001:3984:3989::11
    volumes:
      - dble_1_cgroup:/sys/fs/cgroup
      - /share:/share
    working_dir: /opt

  clickhouse-1:
      image: dble/dble_test_clickhouse
      container_name: clickhouse-server_1
      hostname: clickhouse-server_1
      privileged: true
      stdin_open: true
      tty: true
      ports:
          - "18123:8123"
          - "19000:9000"
          - "19004:9004"
      networks:
          dble-net:
            ipv4_address: 172.100.9.10
  clickhouse-2:
      image: dble/dble_test_clickhouse
      container_name: clickhouse-server_2
      hostname: clickhouse-server_2
      privileged: true
      stdin_open: true
      tty: true
      ports:
          - "28123:8123"
          - "29000:9000"
          - "29004:9004"
      networks:
          dble-net:
            ipv4_address: 172.100.9.11