# Created by Rita at 2018/11/1
Feature: #navicat.feature
  # related sqls would be sent when  Navicat Premium 12 connect dble,and dble should support these sqls

  Scenario: # test if dble support related sqls
    Then execute sql in "dble-1" in "user" mode
  | user         | passwd         | conn    | toClose | sql                                                                                                                                                                                              | expect        | db     |
  | test         | 111111         | conn_0 | False    | SELECT TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE FROM information_schema.TABLES WHERE TABLE_SCHEMA = 'mytest' ORDER BY TABLE_SCHEMA, TABLE_TYPE                                 | length{(0)}  | mytest |
  | test         | 111111         | conn_0 | False    | SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, COLUMN_TYPE FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'mytest' ORDER BY TABLE_SCHEMA,TABLE_NAME                 | length{(0)}  | mytest |
  | test         | 111111         | conn_0 | False    | SELECT DISTINCT ROUTINE_SCHEMA, ROUTINE_NAME, PARAMS.PARAMETER FROM information_schema.ROUTINES LEFT JOIN ( SELECT SPECIFIC_SCHEMA, SPECIFIC_NAME, GROUP_CONCAT(CONCAT(DATA_TYPE, ' ', PARAMETER_NAME) ORDER BY ORDINAL_POSITION SEPARATOR ', ') PARAMETER, ROUTINE_TYPE FROM information_schema.PARAMETERS GROUP BY SPECIFIC_SCHEMA, SPECIFIC_NAME, ROUTINE_TYPE ) PARAMS ON ROUTINES.ROUTINE_SCHEMA = PARAMS.SPECIFIC_SCHEMA AND ROUTINES.ROUTINE_NAME = PARAMS.SPECIFIC_NAME AND ROUTINES.ROUTINE_TYPE = PARAMS.ROUTINE_TYPE WHERE ROUTINE_SCHEMA = 'mytest' ORDER BY ROUTINE_SCHEMA | length{(0)} | mytest |
  | test         | 111111         | conn_0 | False    | SELECT TABLE_NAME, CHECK_OPTION, IS_UPDATABLE, SECURITY_TYPE, DEFINER FROM information_schema.VIEWS WHERE TABLE_SCHEMA = 'mytest' ORDER BY TABLE_NAME ASC                | length{(0)}   | mytest |
  | test         | 111111         | conn_0 | False    | SELECT * FROM information_schema.ROUTINES WHERE ROUTINE_SCHEMA = 'mytest' ORDER BY ROUTINE_NAME                                                                                    | length{(0)}   | mytest |
  | test         | 111111         | conn_0 | True     | SELECT DISTINCT ROUTINE_SCHEMA, ROUTINE_NAME, PARAMS.PARAMETER FROM information_schema.ROUTINES LEFT JOIN ( SELECT SPECIFIC_SCHEMA, SPECIFIC_NAME, GROUP_CONCAT(CONCAT(DATA_TYPE, ' ', PARAMETER_NAME) ORDER BY ORDINAL_POSITION SEPARATOR ', ') PARAMETER, ROUTINE_TYPE FROM information_schema.PARAMETERS GROUP BY SPECIFIC_SCHEMA, SPECIFIC_NAME, ROUTINE_TYPE ) PARAMS ON ROUTINES.ROUTINE_SCHEMA = PARAMS.SPECIFIC_SCHEMA AND ROUTINES.ROUTINE_NAME = PARAMS.SPECIFIC_NAME AND ROUTINES.ROUTINE_TYPE = PARAMS.ROUTINE_TYPE WHERE ROUTINE_SCHEMA = 'mytest' ORDER BY ROUTINE_SCHEMA| length{(0)} | mytest |