#!default_db:schema1
#Single-table Synate
#UPDATE [LOW_PRIORITY] [IGNORE] table_name SET col_name1={expr1} [,col_name2={expr2}] ...
#[LOW_PRIORITY],[IGNORE] Invalid
DROP TABLE IF EXISTS test1
CREATE TABLE test1 (id INT(11) PRIMARY KEY,R_REGIONKEY INT(11),R_NAME VARCHAR(50),R_COMMENT VARCHAR(50))
INSERT INTO test1 (id,R_REGIONKEY,R_NAME,R_COMMENT) VALUES (1,1, 'Eastern','test001'),(3,3, 'Northern','test003'),(2,2, 'Western','test002'),(4,4, 'Southern','test004')
#UPDATE test1 SET id = 3
#SELECT * FROM test1
UPDATE test1 SET R_REGIONKEY=1,R_NAME='test1',R_COMMENT="test11"
SELECT * FROM test1
UPDATE test1 SET R_REGIONKEY=R_REGIONKEY+10
SELECT id,R_REGIONKEY FROM test1
UPDATE LOW_PRIORITY test1 SET R_REGIONKEY=R_REGIONKEY+10
SELECT id,R_REGIONKEY FROM test1
UPDATE IGNORE test1 SET R_REGIONKEY=R_REGIONKEY+10
SELECT id,R_REGIONKEY FROM test1
UPDATE test1 SET id=id+1
SELECT id,R_REGIONKEY FROM test1
UPDATE test1 SET id=id-1
SELECT id,R_REGIONKEY FROM test1
UPDATE test1 SET id=10 WHERE id=4 OR id=1 AND id=3
SELECT id,R_REGIONKEY FROM test1
#
#UPDATE table_name SET col_name1={DEFAULT}[,col_name2={expr2}]...
DROP TABLE IF EXISTS test1
CREATE TABLE test1 (id INT(11) NOT NULL DEFAULT 1,R_REGIONKEY INT(11),R_NAME VARCHAR(50) DEFAULT 'test',R_COMMENT VARCHAR(50))
INSERT INTO test1 (id,R_REGIONKEY,R_NAME,R_COMMENT) VALUES (1,1, 'Eastern','test001'),(3,3, 'Northern','test003'),(2,2, 'Western','test002'),(4,4, 'Southern','test004')
#UPDATE test1 SET id=DEFAULT
#SELECT * FROM test1
UPDATE test1 SET R_NAME=DEFAULT,R_REGIONKEY=1
SELECT * FROM test1
#
#UPDATE table_name SET col_name1={DEFAULT}[,col_name2={expr2}]... [WHERE where_condition]
DROP TABLE IF EXISTS test1
CREATE TABLE test1 (id INT(11) NOT NULL DEFAULT 1,test INT,detail VARCHAR(20) DEFAULT 'test')
INSERT INTO test1 (id,test,detail) VALUES (1,1,'mydetail'),(2,2,'mydetail'),(3,3,'mydetail'),(4,4,'mydetail'),(12,12,'mydetail')
UPDATE test1 SET detail=DEFAULT WHERE test<10
SELECT * FROM test1
DROP TABLE IF EXISTS test1
CREATE TABLE test1 (id INT(11),R_REGIONKEY INT(11) PRIMARY KEY,R_NAME VARCHAR(50),R_COMMENT VARCHAR(50))
INSERT INTO test1 (id,R_REGIONKEY,R_NAME,R_COMMENT) VALUES (1,1, 'Eastern','test001'),(3,3, 'Northern','test003'),(2,2, 'Western','test002'),(4,4, 'Southern','test004')
UPDATE test1 SET R_REGIONKEY=10 WHERE R_REGIONKEY=4 OR R_REGIONKEY=1 AND R_REGIONKEY=3
SELECT * FROM test1
UPDATE test1 SET R_NAME='aly' WHERE id>0
SELECT * FROM test1
UPDATE test1 SET R_NAME='test' WHERE id=1
SELECT * FROM test1
UPDATE test1 SET R_NAME='test1' WHERE id IN (1,2,3)
SELECT * FROM test1
UPDATE test1 SET R_NAME='test1' WHERE id NOT IN (1,2,3)
SELECT * FROM test1
UPDATE test1 SET R_NAME='test2' WHERE id BETWEEN 1 AND 3
SELECT * FROM test1
UPDATE test1 SET R_REGIONKEY=200 WHERE R_NAME='test'
SELECT * FROM test1
UPDATE test1 SET R_REGIONKEY=401 WHERE R_NAME LIKE '%aly%'
SELECT * FROM test1
UPDATE test1 SET R_REGIONKEY=R_REGIONKEY+10 WHERE R_REGIONKEY>=2 order by R_NAME LIMIT 1
SELECT * FROM test1
DROP TABLE IF EXISTS test1
#
#clear tables
#
DROP TABLE IF EXISTS test1
DROP TABLE IF EXISTS test1