version: 1
disable_existing_loggers: True

formatters:
  simple:
    format: "[%(asctime)s][%(levelname)5s][%(filename)20s][%(lineno)4d][%(funcName)s][%(message)s]"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  debug_file_handler:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: logs/behave_debug.log
    mode: a
  info_file_handler:
    class: logging.FileHandler
    level: INFO
    formatter: simple
    filename: logs/behave_info.log
    mode: a
  error_file_handler:
    class: logging.FileHandler
    level: ERROR
    formatter: simple
    filename: logs/behave_error.log
    mode: a

loggers:
  # filter paramiko low level log
  paramiko:
    level: WARNING
    handlers:
      - debug_file_handler
    propagate: False
  root:
    level: DEBUG
    handlers:
      - debug_file_handler
      - info_file_handler
      - error_file_handler