---
version: 1
disable_existing_loggers: True

formatters:
  simple:
    format: "[%(asctime)s][%(levelname)8s][%(filename)15s][%(lineno)4d][%(funcName)s][%(message)s]"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: sys.stdout
  info_file_handler:
    class: logging.FileHandler
    level: INFO
    formatter: simple
    filename: logs/behave_info.log
    mode: a
  debug_file_handler:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: logs/behave_debug.log
    mode: a
  error:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: simple
    filename: logs/behave_error.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8
loggers:
  steps:
    level: DEBUG
    handlers:
      - info_file_handler
      - debug_file_handler
  lib:
    level: DEBUG
    handlers:
      - debug_file_handler
  environment:
    level: DEBUG
    handlers:
      - info_file_handler
      - debug_file_handler
  paramiko.transport:
    level: INFO
    handlers:
      - debug_file_handler
  root:
    level: DEBUG
    handlers:
      - info_file_handler
      - debug_file_handler